name: deploy

on:
  push:
    branches:
      - deploy-fe   

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
        
      - name: Install Dependencies
        run: yarn
        working-directory: ./client
        
      - name: Build
        run: yarn build
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }} 
          REACT_APP_OAUTH_URL: ${{ secrets.REACT_APP_OAUTH_URL }}
          CI: ""
        working-directory: ./client

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_CLIENT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CLIENT }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://seb42-main-026-fe
        working-directory: ./client
